language: scala
jdk: oraclejdk8
script: ./.travis.sh
cache:
  directories:
  - $HOME/.cache
  - $HOME/.ivy2/cache
  - $HOME/.sbt
git:
  depth: false
before_install:
  - source scripts/website/setup-build-tools.sh
sudo: required
stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)
  - name: upload-launcher
    if: tag IS present
  - name: update-versioned-docs
    if: (branch = debug-ci AND type = push) OR (tag IS present)
  - name: update-website
    if: (branch = debug-ci AND type = push) OR (tag IS present)
jobs:
  include:
  - stage: release
    script: sbt ci-release
  - stage: upload-launcher
    name: "Upload launcher"
    script: scripts/upload-launcher.sh
  - stage: update-versioned-docs
    env: WEBSITE_DIR=docs/website VERSIONED_DOCS_REPO=almond-sh/versioned-docs
    script:
      - amm scripts/site.sc --publishLocal true --npmInstall true --yarnRunBuild true
      - export TRAVIS_TAG=v0.2.1
      - scripts/website/versioned-docs.sh --update
  - stage: update-website
    env: WEBSITE_DIR=docs/website REPO=alexarchambault/test-almond-gh-pages VERSIONED_DOCS_REPO=almond-sh/versioned-docs
    name: "Push website"
    script:
      - export TRAVIS_TAG=v0.2.1
      - scripts/website/versioned-docs.sh
      - amm scripts/site.sc --publishLocal true --npmInstall true --yarnRunBuild true --relativize true
      - scripts/website/push-website.sh
branches:
  only:
  - master
  - debug-ci
  - /^v\d+\.\d+.*$/ # tagged versions
